CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar(30) NOT NULL,
  "lastname" varchar(30) NOT NULL,
  "email" varchar(40) NOT NULL,
  "password" varchar(20) NOT NULL,
  "age" int NOT NULL,
  "id_rol" int NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int NOT NULL,
  "id_course" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_curse" varchar(50) NOT NULL,
  "description" varchar(250) NOT NULL,
  "level" varchar(30) NOT NULL
);

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_video" varchar(50) NOT NULL,
  "url" varchar(250) NOT NULL
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_course" int NOT NULL,
  "id_video" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_categories" varchar(35) NOT NULL
);

CREATE TABLE "courses_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_course" int NOT NULL,
  "id_categori" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_role" varchar(30) NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id_rol") REFERENCES "roles" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("id_categori") REFERENCES "categories" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("id_video") REFERENCES "videos" ("id");


INSERT INTO roles (name_role) VALUES('student'),('teacher'),('admin');

INSERT INTO users (firstname, lastname,  email, password, age, id_rol) VALUES('Alicia','Hernandez','alicia.hernandez@example.com','y1$8m#Kt', 29, 1),('Gabriel','Martinez','gabriel.martinez@example.com','B2t#7f$m',42, 2 ),('Sofia','Rodriguez','sofia.rodriguez@example.com','p8#5Ck@r',25, 1 ), ('Javier','Perez','javier.perez@example.com','M3q#9x$L',37, 3 ), ('Maria','Gonzalez','maria.gonzalez@example.com','f5#pK7^t',31, 1 );

INSERT INTO courses (title_curse, description, level) VALUES('Introduction to Python','Learn the basics of Python programming language and start coding like a pro.','Beginner'),('Data Science Fundamentals','Get started with data science and learn how to analyze data using Python.','Intermediate'),('Digital Marketing','Learn how to create and implement successful digital marketing campaigns.','Intermediate'),('Cybersecurity','Discover the fundamentals of cybersecurity and learn how to protect your systems.','Advanced');

INSERT INTO users_courses (id_user, id_course) VALUES(1,1),(1,2),(2,2),(2,3),(3,3);



